{% set name = "soilgrids" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gantian127/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f2dc15667ec9d7a872a67fec13f4cca8e251144873668a33d19ace2e60e943c3

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - soilgrids=soilgrids.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - rioxarray
    - xarray
    - requests
    - pyyaml
    - click
    - bmipy
    - netcdf4
    - owslib

test:
  requires:
    - python {{ python_min }}
  imports:
    - soilgrids

about:
  home: https://github.com/gantian127/soilgrids
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: |
    A Python library to fetch the global gridded soil information from SoilGrids system
  description: |
    soilgrids provides a set of functions that allow downloading of the global gridded 
    soil information from SoilGrids, a system for global digital soil mapping to map the 
    spatial distribution of soil properties across the globe. 
    soilgrids also includes a Basic Model Interface (BMI), which converts the SoilGrids 
    dataset into a reusable, plug-and-play data component (pymt_soilgrids) for the PyMT 
    modeling framework developed by Community Surface Dynamics Modeling System (CSDMS).
  doc_url: https://soilgrids.readthedocs.io
  dev_url: https://github.com/gantian127/soilgrids

extra:
  recipe-maintainers:
    - gantian127
